### ISSUE TITLE
Front end error

### ISSUE THREAD

**Issue by S-Burns** [silvestrevivo/solana-svelte-counter#18]
$'npm run dev'

'
TypeError: Cannot read properties of undefined (reading 'address')
    at eval (/src/lib/AnchorConnectionProvider.svelte:27:47)
    at Object.$$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at eval (/src/routes/__layout.svelte:46:103)
    at Object.$$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at root.svelte:37:45
    at $$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at Object.render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1692:26)
    at render_response (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1070:28)
    at async respond_with_error (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1691:10)
    at async respond$1 (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1942:4)

TypeError: Cannot read properties of undefined (reading 'address')
    at eval (/src/lib/AnchorConnectionProvider.svelte:27:47)
    at Object.$$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at eval (/src/routes/__layout.svelte:46:103)
    at Object.$$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at root.svelte:37:45
    at $$render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1684:22)
    at Object.render (/mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/svelte/internal/index.js:1692:26)
    at render_response (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1070:28)
    at async respond_with_error (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1691:10)
    at async respond$1 (file:///mnt/c/Users/shane/Desktop/solana-svelte-counter/solana-svelte-counter/app/node_modules/@sveltejs/kit/dist/chunks/index.js:1942:4)

'

**Comment by silvestrevivo** [comment]
@S-Burns thanks for opening the issue. I think in you IDL is missing the next information: 

```
"metadata": {
    "address": "<your program id>"
  }
```

Let me know it that makes sense.
